steps:
# Git checkout
- name: 'gcr.io/cloud-builders/git'
  args: ['checkout', 'master']

# Maven build
- name: 'maven:3.8.1-openjdk-11'
  entrypoint: 'mvn'
  args: ['clean', 'install']

# Docker build
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/grafana-monitoring-demo/onlinebookstore-0.0.1:$COMMIT_SHA', '-f', 'Dockerfile', '.']
images:
- 'gcr.io/grafana-monitoring-demo/onlinebookstore-0.0.1:$COMMIT_SHA'
