steps:
# Git checkout
- name: 'gcr.io/cloud-builders/git'
  args: ['checkout', 'master']

# Maven build
- name: 'maven:3.8.1-openjdk-11'
  entrypoint: 'mvn'
  args: ['clean', 'install']

# Docker build and push
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/grafana-monitoring-demo/demo:$COMMIT_SHA', '-f', 'Dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/grafana-monitoring-demo/cloud-build-repo/demo:$COMMIT_SHA']
images:
- 'gcr.io/grafana-monitoring-demo/demo:$COMMIT_SHA'



